M48
; DRILL file {KiCad 9.0.7} date 2026-03-24T21:53:23-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-24T21:53:23-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X69.355Y-57.3
X69.355Y-63.08
T2
X66.53Y-49.67
X66.53Y-107.67
X89.53Y-49.67
X89.53Y-107.67
M30
